### PR TITLE
CP-12148: Replace platform: pci_pv to new field auto_update_drivers

### PR DESCRIPTION
**Pull request by cheng--zhang**
Add auto_update_drivers in Vm.t
Signed-off-by: chengz <cheng.zhang@citrix.com>

### CODE REVIEW

**Comment by jonludlam** [comment]
Hi @cheng--zhang - as discussed on slack, we'll need the upgrade code here, see  https://github.com/mirage/ocaml-rpc/blob/master/tests/idl_test.ml#L22 for an example of how to do this.

**Comment by jonludlam** [comment]
In fact, this is sufficiently complicated that I'm gonna have a go at doing the upgrade logic myself

**Comment by cheng--zhang** [comment]
Hi @jonludlam 
Thanks a lot for your great help.
Will made new pull request when #60 merged.

**Comment by robhoes** [comment]
Shouldn't this have been a pull request to the trunk-car1755 branch?

**Pull request closed without merging**
