### PR TITLE
CP-36919,CP-36711: Update ciphers used by stunnel/XAPI for Trunk

### PR DESCRIPTION
**Pull request by minglumlu**
Signed-off-by: Ming Lu <ming.lu@citrix.com>

### CODE REVIEW

**Comment by psafont** [comment]
Please add to the commit message that we want more than a single cipher to be used and that's why we're introducing `ECDHE-RSA-AES128-GCM-SHA256`.

**Review by lippirk — APPROVED** [review]

**Comment by minglumlu** [comment]
> Please add to the commit message that we want more than a single cipher to be used and that's why we're introducing `ECDHE-RSA-AES128-GCM-SHA256`.

Sure. The commit message has been updated.

**Comment by Zhengchai** [comment]
is this CA still valid to change the cipher's order together?
https://issues.citrite.net/browse/CA-329107

**Comment by minglumlu** [comment]
> HI Ming, is this concern on the cipher's order still valid?

Yes. I think the one with longer length of bits should be at first.

**Review by psafont — APPROVED** [review]

**Pull request merged**
