### PR TITLE
ci: fix compilation errors

### PR DESCRIPTION
**Pull request by lippirk**
#321 contained compilation errors, so I suggest that we revert the patch. The CI should really be catching this

### CODE REVIEW

**Comment by psafont** [comment]
Compilation error is:
```
make all
dune build @all --profile=release
File "misc/channel_helper.ml", line 91, characters 24-52:
91 |     Lwt_unix.ADDR_INET (Lwt_unix.inet_addr_of_string unwrapped_ip, port)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Lwt_unix.inet_addr_of_string
```

**Review by psafont — APPROVED** [review]

**Comment by benjamreis** [comment]
The code should be 
```ocaml
Lwt_unix.ADDR_INET (Unix.inet_addr_of_string unwrapped_ip, 0)
```

I'll create a new PR after the revert is merged.

**Review by benjamreis — APPROVED** [review]

**Comment by lindig** [comment]
What is the state of this PR? I'd be happy to review it but the discussion suggests there is a dependency on some other action.

**Comment by psafont** [comment]
This is ready to be reviewed, there will be a another PR fixing the issue caused by the code that's being rolled back.

**Review by edwintorok — APPROVED** [review]

**Pull request merged**
