### PR TITLE
CP-12250: New vGPU interface

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
`xen-git` says no:

```
+ ocamlfind ocamlc -c -g -package xcp.xen -package xcp -package uuidm -package threads -package rpclib -package cmdliner -thread -I src -o src/xn.cmo src/xn.ml
File "src/xn.ml", line 146, characters 44-50:
Error: The record type Xenops_interface.Pci.t has no field domain
```

**Comment by johnelse** [comment]
Yeah, this needs to go in at the same time as the corresponding xenopsd and xapi changes.

**Comment by simonjbeaumont** [comment]
why is travis happy?

**Comment by johnelse** [comment]
Because it's not trying to build the whole of api-libs, just xcp-idl.

**Comment by robhoes** [comment]
This looks good to me, given the design at http://xapi-project.github.io/features/futures/gpu-support-evolution.html.

**Pull request merged**
