### PR TITLE
CP-12093: Add PIF_metrics.is_fcoe_supported RPC to Network Interface

### PR DESCRIPTION
**Pull request by sharady**
This call will return the status of PIF
whether it supports FCoE

Signed-off-by: sharad yadav <sharad.yadav@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
This looks fine to me. There are dependent pull requests with further actions (on xen-api and xcp-networkd), so I won't merge this yet until the other ones are ready.

**Comment by robhoes** [comment]
I've requested a design change, which will require a change to this patch.

**Comment by robhoes** [comment]
This now looks good, and can go in together with the other patches.

**Comment by robhoes** [comment]
@sharady Actually, please squash the patches first.

**Comment by sharady** [comment]
Thanks @robhoes , for the review.
I have squashed the commits.

**Pull request merged**
