### PR TITLE
Attempt to fix the travis build

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by johnelse** [comment]
Just triggering the CI - don't merge!

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by euanh** [comment]
#=== ERROR while installing xapi-idl.0.11.0 ===================================#

# opam-version 1.2.1

# os           linux

# command      make all

# path         /home/travis/.opam/system/build/xapi-idl.0.11.0

# compiler     system (4.02.1)

# exit-code    2

# env-file     /home/travis/.opam/system/build/xapi-idl.0.11.0/xapi-idl-7991-1872ec.env

# stdout-file  /home/travis/.opam/system/build/xapi-idl.0.11.0/xapi-idl-7991-1872ec.out

# stderr-file  /home/travis/.opam/system/build/xapi-idl.0.11.0/xapi-idl-7991-1872ec.err

### stderr ###

# W: Field 'pkg_message_switch_version_ge_0_11_0' is not set: Cannot satisfy version constraint on pkg_message_switch: >= 0.11.0 (version: 0.10.4)
```
# E: Cannot find findlib package message_switch (>= 0.11.0)

# E: Failure("1 configuration error")
```
# make: *** [setup.data] Error 1

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by djs55** [comment]
```
# File "xen/xenops_interface.ml", line 277, characters 20-37:
# Error: Unbound value Rpc.struct_extend
# Command exited with code 2.
### stderr ###
# E: Failure("Command ''/usr/bin/ocamlbuild' lib/libxcp_stubs.a lib/dllxcp_stubs.so lib/xcp.cma lib/xcp.cmxa lib/xcp.a lib/xcp.cmxs storage/xcp_storage.cma storage/xcp_storage.cmxa storage/xcp_storage.a storage/xcp_storage.cmxs storage/storage_test.native network/xcp_network.cma network/xcp_network.cmxa network/xcp_network.a network/xcp_network.cmxs rrd/xcp_rrd.cma rrd/xcp_rrd.cmxa rrd/xcp_rrd.a rrd/xcp_rrd.cmxs xen/xcp_xen.cma xen/xcp_xen.cmxa xen/xcp_xen.a xen/xcp_xen.cmxs xen/xen_test.native memory/xcp_memory.cma memory/xcp_memory.cmxa memory/xcp_memory.a memory/xcp_memory.cmxs lib/channel_helper.native lib_test/test.native example/example.native -tag debug -tag tests -j 4' terminated with error code 10")
# make: *** [build] Error 1
```

**Comment by euanh** [comment]
```
# File "xen/xenops_interface.ml", line 277, characters 20-37:
# Error: Unbound value Rpc.struct_extend
# Command exited with code 2.
### stderr ###
# E: Failure("Command ''/usr/bin/ocamlbuild' lib/libxcp_stubs.a lib/dllxcp_stubs.so lib/xcp.cma lib/xcp.cmxa lib/xcp.a lib/xcp.cmxs storage/xcp_storage.cma storage/xcp_storage.cmxa storage/xcp_storage.a storage/xcp_storage.cmxs storage/storage_test.native network/xcp_network.cma network/xcp_network.cmxa network/xcp_network.a network/xcp_network.cmxs rrd/xcp_rrd.cma rrd/xcp_rrd.cmxa rrd/xcp_rrd.a rrd/xcp_rrd.cmxs xen/xcp_xen.cma xen/xcp_xen.cmxa xen/xcp_xen.a xen/xcp_xen.cmxs xen/xen_test.native memory/xcp_memory.cma memory/xcp_memory.cmxa memory/xcp_memory.a memory/xcp_memory.cmxs lib/channel_helper.native lib_test/test.native example/example.native -tag debug -tag tests -j 4' terminated with error code 10")
# make: *** [build] Error 1
```

**Comment by euanh** [comment]
@djs55: Snap!

**Comment by djs55** [comment]
See [ocaml/opam-repository#4097]

**Comment by djs55** [comment]
I think it needs a version constraint on rpc >= 1.5.3

**Comment by johnelse** [comment]
Good idea!

**Comment by djs55** [comment]
You beat me to it ;)

**Comment by robhoes** [comment]
You snooze you lose

**Pull request merged**
