### PR TITLE
[CP-22597] Add other_config to vgpu records for temporary migration vgpu_map

### PR DESCRIPTION
**Pull request by mseri**
This goes hand in hand with https://github.com/xapi-project/xen-api/pull/3073

### CODE REVIEW

**Comment by thomassa** [comment]
Please would you make it clearer in the commit-message that it is the data that is stored temporarily?
(Rather than this code-change being temporary.)

**Comment by thomassa** [comment]
Oh, and you mean "hand in hand with".
"Hand to hand" usually describes combat.

**Comment by thomassa** [comment]
The code looks fine though!

The automatic test failed because it couldn't install shared-block-ring 2.3.0 so it didn't get as far as trying to build the newly changed code. You've mentioned that you've built this and tried it out though, so I'm happy for this to be merged.

**Comment by mseri** [comment]
The tests cannot pass anyway as some of the branches for the vgpu-migration code are still private

**Comment by mseri** [comment]
Message has been updated, merging

**Pull request merged**
