### PR TITLE
CP-15358: support external ip address setting

### PR DESCRIPTION
**Pull request by Chunjie**
set-ip(v4,v6)-configuration

Signed-off-by: Chunjie Zhu <chunjie.zhu@citrix.com>

### CODE REVIEW

**Comment by thomassa** [comment]
@xent-git Test this please

**Comment by thomassa** [comment]
@xen-git Test this please

**Comment by robhoes** [comment]
Replaces #110.

**Comment by robhoes** [comment]
My final comment from the previous PR has not yet been taking into account: "Include the following patch to add upgrade logic for the new fields: robhoes@85b82b5"

**Comment by Chunjie** [comment]
Hi @robhoes ,

I add your patch.

**Comment by robhoes** [comment]
Ok, this one is good now.

**Pull request merged**
