### PR TITLE
CA-328130 add speed to Vusb record

### PR DESCRIPTION
**Pull request by lippirk**
Signed-off-by: lippirk <ben.anson@citrix.com>

### CODE REVIEW

**Comment by lindig** [comment]
Can we un-draft this and merge it?

**Comment by psafont** [comment]
This needs the corresponding PRs from [xenopsd](https://github.com/xapi-project/xenopsd/pull/683) and [xen-api](https://github.com/xapi-project/xen-api/pull/3984) to be ready. I think they still needed some more testing.

**Comment by lippirk** [comment]
Yes, it's not quite ready yet - I still need to verify the fix with the customer

**Comment by lindig** [comment]
Any updates on this?

**Comment by lippirk** [comment]
> Any updates on this?

Unfortunately I have not heard from the customer in a while. I think it is best to leave this unmerged for now. If the number of PRs is bothering you feel free to close :)

**Comment by lindig** [comment]
I think the commits should be squashed into one or two.

**Comment by edwintorok** [comment]
If we've tested this and it works for existing USB devices I think we should merge this, and if there are any remaining bugs we'll fix them (it'll be easier once we have the speed defined at least).

**Pull request merged**
