### PR TITLE
CP-23093: Add igmp_snooping field for bridge

### PR DESCRIPTION
**Pull request by fillzero**
Signed-off-by: Liang Dai <liang.dai1@citrix.com>

### CODE REVIEW

**Comment by fillzero** [comment]
RP https://github.com/xapi-project/xcp-networkd/pull/107 depends on this.

**Comment by fillzero** [comment]
Updated this PR based on @robhoes' suggestion on https://github.com/xapi-project/xcp-networkd/pull/107

**Comment by robhoes** [comment]
We need a xen-api patch before this can be merged, otherwise the build will be broken.

**Comment by robhoes** [comment]
I'll close this for now. When the xen-api patch is ready, I'll reopen and merge this PR.

**Pull request merged**
