### PR TITLE
CA: 272180: Make xenopsd report the request that makes a shutdown to fail

### PR DESCRIPTION
**Pull request by psafont**
Adding the shutdown request that failed allows xapi to inform the users better.

Also since the `shutdown_request` type is going to be used both in `xen-api` and `xenopsd`, add it here.

### CODE REVIEW

**Comment by edwintorok** [comment]
It is usually useful to provide links to related PRs (they all have to go in at once otherwise the build breaks):
https://github.com/xapi-project/xcp-idl/pull/263
https://github.com/xapi-project/xenopsd/pull/593
https://github.com/xapi-project/xen-api/pull/3801

**Comment by edwintorok** [comment]
Looks like the unit tests have failed:
``` 
[exception] Idl_test_common.MarshalError("Expecting String or Enum when unmarshalling a variant")
```
You can try to reproduce it  locally with `make test`

**Comment by edwintorok** [comment]
We had a look this is because the ppx doesn't support generating backwards compatibility code for a variant that didn't use to take an argument to a variant that now takes an argument, the wire format is too different.
Would be better to add a second variant instead for now.

**Comment by rwdrich** [comment]
Did you remove `shutdown_request` with your fixup?

**Pull request merged**
