### PR TITLE
 Merge ppx_trunk into master for OCaml 4.02.3 and PPX

### PR DESCRIPTION
**Pull request by lindig**
c41b428 2017-02-08 (HEAD -> ppx_trunk, tag: v1.90.1, github-xapi/ppx_trunk) Use PPXs where possible [Jon Ludlam]
    8bf3ea9 2017-02-09 (github-xapi/master) Merge pull request #141 from jonludlam/no-more-lwt-syntax [GitHub]

    Signed-off-by: Christian Lindig <christian.lindig@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
There is another pending PR, https://github.com/xapi-project/xcp-idl/pull/144, so probably we should merge that first. Then we should update the spec file changes to include that change as well.

We should also move the version tag, and change the version numbers and the CHANGELOG in this repo before the new release, as done by https://github.com/xapi-project/xcp-idl/commit/02571c368bc128f90f3a35128351a86e93a6f323

**Comment by mseri** [comment]
We need to document more explicitly now that changes in certain libraries will require updating the xs-opam-repo. Maybe this should go in the README

**Comment by gaborigloi** [comment]
We could devise a standard text that we put into the README of every affected package.

**Comment by mseri** [comment]
Seems sound

**Comment by lindig** [comment]
I have accepted https://github.com/xapi-project/xcp-idl/pull/144

**Pull request merged**
