### PR TITLE
CP-24549: Add vusb to xenops_interface

### PR DESCRIPTION
**Pull request by taoyongd**
1. Add vusb to xenops_interface with plug/unplug interface

Signed-off-by: Taoyong Ding <taoyong.ding@citrix.com>

### CODE REVIEW

**Comment by taoyongd** [comment]
PR https://github.com/xapi-project/xenopsd/pull/393  will depend on this .

**Comment by huizh** [comment]
Hi @jonludlam, for another PR xapi-project/xenopsd#393 depends on this one and this has been approved by @lindig, please could you merge this PR?

Thanks.

**Comment by taoyongd** [comment]
Hi @jonludlam  @lindig @robhoes , can this PR be merged  now, as PR https://github.com/xapi-project/xen-api/pull/3239 and https://github.com/xapi-project/xenopsd/pull/393 depend on this.
Thanks

**Comment by jonludlam** [comment]
I think this PR looks good to me.

**Pull request merged**
