### PR TITLE
CA-201107: Support dynamic logging suppression

### PR DESCRIPTION
**Pull request by euanh**

### CODE REVIEW

**Comment by euanh** [comment]
The boolean entry in the hash table is not used - the hash is just a set.

**Comment by robhoes** [comment]
Travis says that the unit test is failing:
```
- 2016-03-04T15:56:22+00:00 testing-gce-2b817680-aa33-425e-ae00-b8a5949307bd#00 E: Test xcp:4:debug:4:Test Debug.set_level (multiple loggers) has failed.
- 2016-03-04T15:56:22+00:00 testing-gce-2b817680-aa33-425e-ae00-b8a5949307bd#00 E: not equal in test xcp:4:debug:4:Test Debug.set_level (multiple loggers).
```

**Comment by euanh** [comment]
I originally had `compare l level < 0`, however the manual says that the comparison operators are valid for all types and are compatible with `compare`: http://caml.inria.fr/pub/docs/manual-ocaml/libref/Pervasives.html

**Comment by djs55** [comment]
BTW you should check out Daniel's new logging library -- it's quite good. Check out: https://github.com/mirage/mirage-block-unix/blob/ef3d1559200b8ca88baa3cc6f987cdc7d48aae45/lib/block.ml#L103

My favourite features are
- if logging at a level is off, the function is never evaluated and the big string is not created
- it comes with pluggable backends ("reporters")

If you wanted to, you could start using it incrementally and retire some of the custom logging stuff.

**Comment by euanh** [comment]
@djs55: It's on our list. :)

**Comment by robhoes** [comment]
You can compare those values (by `<` or `compare`) as OCaml defines a total order of the type, even for a variant type like `Syslog.level`. But the order seems quite arbitrary; for variant types it seems that constructors that are defined "earlier" are "smaller". It's probably because of the way they are translated to integers on the heap (which means it wouldn't work anymore of some constructors have arguments).

The type is `type level = Emerg | Alert | Crit | Err | Warning | Notice | Info | Debug`, so indeed `Info < Debug` etc. You can get away with using this if you are willing to rely on no one changing the type. I would be a lot more comfortable with a "compare levels" function in syslog.ml and a comment saying that it relies on the order of the constructors in the type.

**Comment by euanh** [comment]
@robhoes: I'll add a 'more serious than' function, which will be easier to read than a full blown compare.

Originally I had a function to map levels to ints which could then be compared, but that seemed a bit redundant.   At least for the C interface, the language spec states that variants are numbered in order of definition starting at zero: http://caml.inria.fr/pub/docs/manual-ocaml/intfc.html#sec429.   This is quite convenient as it matches the way enums work in C.   We are relying on this definition in the C stubs, which use `Int_val(level)` to index into an array of loglevels, so a change in the order of the items in the type will still break the stubs.

**Comment by robhoes** [comment]
If you add a unit test for the "most serious than" function, then we should be safe! :)

**Pull request merged**
