### PR TITLE
Test the RRD interface

### PR DESCRIPTION
**Pull request by jonludlam**
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

### CODE REVIEW

**Comment by jonludlam** [comment]
Yep, that'd be nice. I'm not planning to put too much effort into the old-school camlp4 stuff though - we can be more creative in the ppx world.

**Comment by mseri** [comment]
Weird error:
```
File "rrd/rrd_interface.pp.ml", line 1, characters 12-13:
Illegal character (\132)
File "rrd/rrd_interface.pp.ml", line 1:
Error: Error while running external preprocessor
Command line: camlp4 '-I' '/home/opam/.opam/4.04.2/lib/xmlm' '-I' '/home/opam/.opam/4.04.2/lib/result' '-I' '/home/opam/.opam/4.04.2/lib/rresult' '-I' '/home/opam/.opam/4.04.2/lib/rpclib' '-I' '/home/opam/.opam/4.04.2/lib/rpclib' '-I' '/home/opam/.opam/4.04.2/lib/rpclib' '-I' '/home/opam/.opam/4.04.2/lib/ocaml/camlp4' '-I' '/home/opam/.opam/4.04.2/lib/rpclib' 'xmlm.cma' 'result.cma' 'rresult.cma' 'rpclib_core.cma' 'xml.cma' 'rpclib.cma' '-parser' 'o' '-parser' 'op' '-printer' 'p' 'idl.cma'  'rrd/rrd_interface.pp.ml' > /tmp/ocamlpp434711
```

**Comment by jonludlam** [comment]
That's pretty unusual...

**Comment by mseri** [comment]
It is still failing in the same way :confused:

**Comment by jonludlam** [comment]
It seems that the failure occurs only when we enable coverage.

**Comment by mseri** [comment]
I would not be surprised if camlp4 and new ppxs are starting fighting more and more

**Comment by mseri** [comment]
It works lovally for me. I’ll merge

**Pull request merged**
