### PR TITLE
[merge together with PR xenserver/xen-api-libs-specs/pull/195] Update OASIS file and remove files generated by OASIS

### PR DESCRIPTION
**Pull request by gaborigloi**
Generate the build files with OASIS as part of the build step.
(See [this pull request](https://github.com/issuu/ocaml-zmq/issues/23) for an interesting discussion of committing files generated by OASIS.)

I'm not sure what the "Custom" field does in the `_oasis` file (even after reading the [OASIS manual](http://oasis.forge.ocamlcore.org/MANUAL.html#executable)), so I left it as it is.

This change also requires an update to the spec files, therefore it should be merged together with https://github.com/xenserver/xen-api-libs-specs/pull/195 .

### CODE REVIEW

**Comment by lindig** [comment]
What about the spec file in `xenserver-specs/SPECS/ocaml-xcp-idl.spec`?

**Comment by gaborigloi** [comment]
@lindig thanks for the heads-up, I'll update the SPEC file in `xenserver-specs` too once https://github.com/xenserver/xen-api-libs-specs/pull/195 is merged. As I said in https://github.com/xenserver/xen-api-libs-specs/pull/195#issuecomment-264819270, as far as I know we don't yet use the SPEC files in `xenserver-specs`, so it's not crucial to get the SPEC file change into `xenserver-specs` in time. But maybe I should submit the same pull request there too so it gets reviewed before anything is merged.

**Comment by gaborigloi** [comment]
Added a `needs updating` label as I think it would be useful to write about the OASIS step in more detail in `INSTALL.md`, for example how to install OASIS.

**Comment by lindig** [comment]
Can this PR still be merged? There was quite a bit of churn in the project since this was opened. I'd like to move ahead and merge it or, or close it for now. The same goes for the related open PR.

**Comment by gaborigloi** [comment]
An additional check we could do when removing files generated by OASIS is to compare the build outputs of the two versions (with and without the generated files). But I'm not sure how likely it is that it will be the same.

**Comment by gaborigloi** [comment]
After we remove the files generated by OASIS from our repos, we will probably need `oasis` in `planex-buildenv`, to run the `oasis setup` step. This shouldn't be a problem, because we have an OASIS package that we did not upstream, with a slightly older version, and we can always install OASIS using OPAM.

**Comment by gaborigloi** [comment]
The build outputs seem to be different, I'm not sure whether that's expected or not.

A possible downside of removing generated files is that the half-generated files such as `Makefile` and `_tags` will always become modified as OASIS will add its own section, and we will have to ignore these changes.

Maybe it isn't worth changing the OASIS build method if we are going to move to topkg anyway, I'm not sure if that's the case.

**Comment by gaborigloi** [comment]
Or maybe we could have a feature branch for this work, for updating the build methods of all our repos, which would involve polishing the `_oasis` files, and removing the generated files?

**Comment by mseri** [comment]
Makes sense, it could maybe be part of the PPX branch where some of the build have to be rewritten and many SPEC files are changed as well. @lindig what do you think?

**Comment by lindig** [comment]
I like the idea to try this on the PPX branch where we have to touch the build-related files. This branch will be merged into `trunk/ring3` and hence it is a good place to try it.

**Comment by mseri** [comment]
Then I am going to close this and https://github.com/xenserver/xen-api-libs-specs/pull/195 
Let's move the changes to the ppx branches instead

**Pull request closed without merging**
