### PR TITLE
Read the whole of the HTTP request, not just the first chunk

### PR DESCRIPTION
**Pull request by simonjbeaumont**
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>

### CODE REVIEW

**Comment by djs55** [comment]
```
DEBUG: File "lib/xcp_client.ml", line 85, characters 40-41:
DEBUG: Error: Unbound value t
DEBUG: Command exited with code 2.
DEBUG: E: Failure("Command ''/usr/bin/ocamlbuild' lib/libxcp_stubs.a lib/dllxcp_stubs.so lib/xcp.cma lib/xcp.cmxa lib/xcp.a lib/xcp.cmxs storage/xcp_storage.cma storage/xcp_storage.cmxa storage/xcp_storage.a storage/xcp_storage.cmxs storage/storage_test.native network/xcp_network.cma network/xcp_network.cmxa network/xcp_network.a network/xcp_network.cmxs rrd/xcp_rrd.cma rrd/xcp_rrd.cmxa rrd/xcp_rrd.a rrd/xcp_rrd.cmxs xen/xcp_xen.cma xen/xcp_xen.cmxa xen/xcp_xen.a xen/xcp_xen.cmxs memory/xcp_memory.cma memory/xcp_memory.cmxa memory/xcp_memory.a memory/xcp_memory.cmxs lib/channel_helper.native lib_test/test.native example/example.native -tag debug -tag tests -j 4' terminated with error code 10")
DEBUG: make: *** [build] Error 1
```

**Comment by simonjbeaumont** [comment]
Yeah. Fixed this locally. Forgot to push :(

-- simon.beaumont@citrix.com (via iPhone)

On 15 Apr 2015, at 18:27, Dave Scott <notifications@github.com<mailto:notifications@github.com>> wrote:


DEBUG: File "lib/xcp_client.ml", line 85, characters 40-41:
DEBUG: Error: Unbound value t
DEBUG: Command exited with code 2.
DEBUG: E: Failure("Command ''/usr/bin/ocamlbuild' lib/libxcp_stubs.a lib/dllxcp_stubs.so lib/xcp.cma lib/xcp.cmxa lib/xcp.a lib/xcp.cmxs storage/xcp_storage.cma storage/xcp_storage.cmxa storage/xcp_storage.a storage/xcp_storage.cmxs storage/storage_test.native network/xcp_network.cma network/xcp_network.cmxa network/xcp_network.a network/xcp_network.cmxs rrd/xcp_rrd.cma rrd/xcp_rrd.cmxa rrd/xcp_rrd.a rrd/xcp_rrd.cmxs xen/xcp_xen.cma xen/xcp_xen.cmxa xen/xcp_xen.a xen/xcp_xen.cmxs memory/xcp_memory.cma memory/xcp_memory.cmxa memory/xcp_memory.a memory/xcp_memory.cmxs lib/channel_helper.native lib_test/test.native example/example.native -tag debug -tag tests -j 4' terminated with error code 10")
DEBUG: make: *** [build] Error 1

**Comment by simonjbeaumont** [comment]
I'll sort it out later tonight. Much later likely.

**Comment by djs55** [comment]
I fixed it up in #56 and merged it.

**Pull request closed without merging**
