### PR TITLE
Fix http header parsing and add unit test

### PR DESCRIPTION
**Pull request by djs55**
The Cohttp_posix_io.Unbuffered_IO module is used everywhere we want to talk HTTP but then hand the fd over to another process, without accidentally buffering any data that process expects.

The HTTP status line was always being read correctly but the headers were always garbled. The headers are often irrelevant, so this wasn't obvious, hence adding a unit test.

### CODE REVIEW

**Comment by euanh** [comment]
@djs55: Could you please rebase this?

**Comment by djs55** [comment]
Rebased, let's see what CI says...

**Comment by euanh** [comment]
It says:
```
+wget https://raw.githubusercontent.com/djs55/ocaml-travisci-skeleton/master/yorick.mli
--2015-05-15 09:02:19--  https://raw.githubusercontent.com/djs55/ocaml-travisci-skeleton/master/yorick.mli
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.75.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.75.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-05-15 09:02:19 ERROR 404: Not Found.
```

:(

**Comment by djs55** [comment]
OK, if travis needs an update anyway we should enable container mode like
this:

https://github.com/talex5/cuekeeper/blob/master/.travis.yml

On Fri, May 15, 2015 at 11:32 AM, Euan Harris <notifications@github.com>
wrote:

> It says:
>
> +wget https://raw.githubusercontent.com/djs55/ocaml-travisci-skeleton/master/yorick.mli
> --2015-05-15 <https://raw.githubusercontent.com/djs55/ocaml-travisci-skeleton/master/yorick.mli--2015-05-15> 09:02:19--  https://raw.githubusercontent.com/djs55/ocaml-travisci-skeleton/master/yorick.mli
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.75.133
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.75.133|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2015-05-15 09:02:19 ERROR 404: Not Found.
>
> :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xapi-project/xcp-idl/pull/18#issuecomment-102364382>.
>



-- 
Dave Scott

**Comment by johnelse** [comment]
I've attempted to fix travis in #64, but it's failing for other reasons...

**Comment by euanh** [comment]
@djs55 - need to rebase again, I'm afraid.

We are now using the upstream version of ocaml-travisci-skeleton.   If you are still using your fork elsewhere, you should probably update.   You are 40 commits behind master, and alas poor yorick.mli isn't in your fork. :)

**Comment by euanh** [comment]
@xen-git: Retest this please.

**Comment by euanh** [comment]
@djs55: See John's comment above. :(

**Comment by johnelse** [comment]
:tada: :shipit: :tada:

**Pull request merged**
