### PR TITLE
Remove outdated INSTALL file

### PR DESCRIPTION
**Pull request by gaborigloi**
The dependencies listed in this file are out of sync with the actual
dependencies of the project, and we could generate a similar, but more
detailed file with the StdFiles OASIS plugin.

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by lindig** [comment]
The existing `INSTALL` file is outdated but I think it is a good practice to provide information how to build a project. I'm not sure what to do here:

* We build projects using RPM but the SPEC file is in a different repository. The SPEC file lists the dependencies and provides instructions how to build.
* We could point to the `opam` file which also includes dependencies and includes build instructions.

**Comment by gaborigloi** [comment]
Agreed, that would be really useful for everyone if we provided build instructions. Maybe we could explain in the README the different methods of building the repository.

I will have a pull request soon for this repository to generate the build files using OASIS, that will also change the build instructions slightly.

**Comment by gaborigloi** [comment]
I've added build instructions to the README, feel free to suggest changes to the wording if the instructions are unclear/incorrect.

**Comment by lindig** [comment]
I think having these generic build instructions is a good idea. When we put these into an `INSTALL` file, we can easily use them for other repos as well. Is it  adding, that an RPM SPEC file can be found at https://github.com/xenserver/xen-api-libs-specs? Or a note that how the code is built inside Citrix is currently changing?

**Comment by gaborigloi** [comment]
@lindig Sounds good, then we have to get it right once, and then we can reuse these generic build instructions for almost every repository. I was thinking about putting these into a separate INSTALL file, but thought it's more visible if it's immediately in the README, depends on what people's expectations are about the location of build instructions; I'm happy to move it to a separate INSTALL file (and I guess a separate INSTALL file is easier to reuse).

I wasn't sure whether it's worth mentioning https://github.com/xenserver/xen-api-libs-specs, because as far as I know we're planning to move away from it to use `xenserver-specs`. But I agree that it would be useful to point people to the SPEC file corresponding to this project, and maybe to the RPM file as well. If we mention now that the way we build code is changing, we will have to update all the build instructions once the changes are done, but that shouldn't be a problem. I think in the future we will use [planex-chroot](https://github.com/mseri/planex-chroot) to build our repositories.

**Comment by lindig** [comment]
Having an `INSTALL` file is common and this would always be a place to check for somebody looking for instructions if they cannot find it in the README. Because we are in a transition and moving spec files in-house, I'm fine with not mentioning them.

I see some potential confusion between a local `opam` file and the one in `opam-repo-dev`.  Is the local `opam` file ever checked that it is working?

I'd like to see a comment from @jonludlam or @euanh about the contents of the generic `INSTALL` file.

**Comment by gaborigloi** [comment]
Good question, and I don't know what the current `opam` file situation is. Our `opam` files are apparently duplicated between our own [`opam-repo-dev`](https://github.com/xapi-project/opam-repo-dev) OPAM repository, and the individual repositories of the different projects.

**Comment by gaborigloi** [comment]
Actually yes, the local `opam` file is checked because Travis CI uses it to build and test the repository using OPAM.

**Comment by lindig** [comment]
So now we have three ways for installation? (1) A Docker container, (2a) `opam-repo-dev`, and (2b) the local `opam` file. I think the INSTALL file should mention this. As far as I can see, the local `opam` file will depend on `opam-repo-dev` because the dependencies in the local `opam` file are described there but are not in the default `opam` repository that OCaml is using otherwise. So the `INSTALL` file could read:

```
Installing as an OPAM package using the
[`opam-repo-dev`](https://github.com/xapi-project/opam-repo-dev) OPAM
repository, possibly in combination with the `opam` file in this repository.
```

**Comment by gaborigloi** [comment]
Thanks, I'll update the `INSTALL.md` to explain that there are two methods of installing the `opam` package. I think (2a) is most useful for a user who just wants to install the package, while (2b) is most useful for a developer who wants to test a change to the local `opam` file and code. The [instructions ("Testing a code change" section)](https://github.com/xapi-project/opam-repo-dev#testing-a-code-change) in the README of `opam-repo-dev` that I linked to from `INSTALL.md` explain method (2b): I think the `opam pin` command in those instructions tells OPAM to use the local `opam` file instead of the one from `opam-repo-dev`. So I think it's enough to just include the text that you proposed, and point the readers to the README of `opam-repo-dev` where everything is explained in detail.

Apparently many of our packages are already there in the [main OPAM repository](https://github.com/ocaml/opam-repository). One important difference between `opam-repo-dev` and the main repo is that we usually have package versions like [`xapi-idl#master`](https://github.com/xapi-project/opam-repo-dev/tree/master/packages/xapi-idl/xapi-idl.xapi-project%23master) in `opam-repo-dev` that track the master branch, while the main OPAM repo only points to fixed versions of `xapi-idl` (the OPAM package corresponding to this repo). So probably we also use `opam-repo-dev` for easy installation of the latest development versions of the different xapi components.

**Comment by lindig** [comment]
I think this is fine but would like @jonludlam to take a look, too.

**Pull request merged**
